--- #YAML:1.0
name:               Mojolicious
version:            0.999934
abstract:           The Web In A Box!
author:
    - Sebastian Riedel <sri@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Carp:                 0
    Cwd:                  0
    Data::Dumper:         0
    Digest::MD5:          0
    Encode:               0
    Errno:                0
    ExtUtils::MakeMaker:  0
    File::Basename:       0
    File::Copy:           0
    File::Path:           0
    File::Spec:           0
    File::Spec::Functions:  0
    File::Temp:           0
    FindBin:              0
    Getopt::Long:         0
    I18N::LangTags:       0
    IO::File:             0
    IO::Poll:             0
    IO::Socket:           0
    Locale::Maketext:     0
    MIME::Base64:         0
    MIME::QuotedPrint:    0
    perl:                 5.008007
    POSIX:                0
    Scalar::Util:         0
    Storable:             0
    Sys::Hostname:        0
    Test::Builder:        0
    Test::Harness:        0
    Test::More:           0
    Time::HiRes:          0
resources:
    bugtracker:   http://github.com/kraih/mojo/issues
    homepage:     http://mojolicious.org
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/mojolicious
    repository:   http://github.com/kraih/mojo
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
